# Generated by Django 5.0.7 on 2024-07-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=100)),
                ('fabricante', models.CharField(default='', max_length=100)),
                ('modelo', models.CharField(default='', max_length=100)),
                ('numero_serie', models.CharField(default='', max_length=16)),
                ('data_compra', models.DateField(null=True)),
                ('valor_compra', models.IntegerField(null=True)),
            ],
        ),
    ]
